export const STRINGS = {
  app: {
    name: 'Blurio',
    splashTagline: 'Offline privacy blur editor',
    sourceLabel: 'Source',
    qualityLabel: 'Quality',
  },
  common: {
    cancel: 'Cancel',
    close: 'Close',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    duplicate: 'Duplicate',
    rename: 'Rename',
    done: 'Done',
    retry: 'Try again',
    continue: 'Continue',
    back: 'Back',
    noProjectSelected: 'No project selected.',
    settings: 'Settings',
    import: 'Import',
    export: 'Export',
    disabled: 'Disabled',
    enabled: 'Enabled',
    yes: 'Yes',
    no: 'No',
  },
  navigation: {
    homeTitle: 'Projects',
    importTitle: 'Import Video',
    editorTitle: 'Editor',
    exportTitle: 'Export',
    settingsTitle: 'Settings',
  },
  home: {
    openSettings: 'Open settings',
    emptyTitle: 'No projects yet',
    emptyBody: 'Import a video to start building blur tracks.',
    emptyButton: 'Create First Project',
    contextTitle: 'Project Actions',
    longPressHint: 'Long press for project actions',
    duplicateAction: 'Duplicate project',
    deleteAction: 'Delete project',
    openAction: 'Open editor',
    deleteConfirmTitle: 'Delete project?',
    deleteConfirmBody: 'This removes metadata and cached previews from this device.',
  },
  import: {
    pickButton: 'Choose from Photos',
    preparing: 'Preparing preview',
    preparingBody: 'Generating thumbnails and local metadata',
    iCloudWarningTitle: 'Asset not fully downloaded',
    iCloudWarningBody:
      'This video appears to be in iCloud only. Download it in Photos first, then re-import.',
    unsupportedTitle: 'Video cannot be opened',
    unsupportedBody: 'The selected file is unsupported or corrupted. Try another video.',
    relinkButton: 'Relink Asset',
    doneButton: 'Open Editor',
  },
  editor: {
    addRegion: 'Add Region',
    regions: 'Regions',
    params: 'Params',
    keyframes: 'Keyframes',
    view: 'View',
    undo: 'Undo',
    redo: 'Redo',
    noTrackTitle: 'No active region',
    noTrackBody: 'Select a region to adjust parameters and keyframes.',
    previewUnavailable: 'Preview unavailable',
    fitToScreen: 'Fit to screen',
    addKeyframe: 'Add keyframe',
    deleteKeyframe: 'Delete keyframe',
    snapHint: 'Snapped to keyframe',
    precisionOn: 'Precision timeline enabled',
    precisionOff: 'Precision timeline disabled',
    markerMenuTitle: 'Keyframe options',
    jumpToMarker: 'Jump to marker',
    editMarker: 'Edit interpolation',
    deleteMarker: 'Delete marker',
    faceTemplate: 'Face area',
    plateTemplate: 'Plate area',
    rectangle: 'Rectangle',
    roundedRect: 'Rounded Rect',
    ellipse: 'Ellipse',
    path: 'Path',
    removeRegion: 'Remove Region',
    saveAsTemplate: 'Save as Template',
    saveTemplateTitle: 'Save Region Template',
    templateNameLabel: 'Template Name',
    templateNamePlaceholder: 'Face blur',
    templateCategoryLabel: 'Category',
    templateCategoryPlaceholder: 'General',
    templateDefaultCategory: 'General',
    applyTemplate: 'Apply Template',
    applyTemplateTitle: 'Apply Template',
    noTemplatesYet: 'No saved templates yet.',
    removeAllRegions: 'Remove All Regions',
  },
  params: {
    strength: 'Strength',
    feather: 'Feather',
    opacity: 'Opacity',
    cornerRadius: 'Corner Radius',
    blendMode: 'Blend mode',
    normal: 'Normal',
    frosted: 'Frosted',
  },
  keyframes: {
    interpolation: 'Interpolation',
    linear: 'Linear',
    easeInOut: 'Ease',
    spring: 'Spring',
    hold: 'Hold',
    parameterControl: 'Parameters',
  },
  view: {
    previewQuality: 'Preview quality',
    guides: 'Guides',
    thumbnails: 'Thumbnails',
    safeAreaOverlay: 'Safe area overlay',
    ultra: 'Ultra',
    balanced: 'Balanced',
    smooth: 'Smooth',
  },
  export: {
    startButton: 'Start Export',
    cancelButton: 'Cancel Export',
    successTitle: 'Export complete',
    successBody: 'Video saved to your photo library path.',
    settingsTitle: 'Export settings',
    stageDecoding: 'Decoding',
    stageApplying: 'Applying blur',
    stageEncoding: 'Encoding',
    stageSaving: 'Saving',
    hdrWarning:
      'HDR preservation is unavailable in fallback mode. The output will be converted to SDR.',
    lowStorageTitle: 'Not enough free space',
    lowStorageBody: 'Free up storage and try export again.',
    toggleSettings: 'Toggle export settings',
    codecLabel: 'Codec',
    codecH264: 'H.264',
    codecHevc: 'HEVC',
    framerateLabel: 'Framerate',
    resolutionLabel: 'Resolution',
    includeAudioLabel: 'Include audio',
    includeAudioOn: 'Audio on',
    includeAudioOff: 'Audio off',
    cancelledLabel: 'Cancelled',
    failedLabel: 'Failed',
  },
  settings: {
    appearance: 'Appearance',
    motion: 'Motion',
    preview: 'Preview',
    export: 'Export',
    storage: 'Storage',
    about: 'About',
    appearanceSystem: 'Match iOS',
    appearanceDark: 'Dark',
    appearanceLight: 'Light',
    reduceMotionSystem: 'Use iOS setting',
    reduceMotionOn: 'Reduced motion on',
    reduceMotionOff: 'Reduced motion off',
    accentColor: 'Accent color',
    previewQualityDefault: 'Default preview quality',
    autoThumbs: 'Generate thumbnails on import',
    safeAreaDefault: 'Show safe area overlay by default',
    clearCache: 'Clear cache',
    storageUsage: 'Estimated project cache',
    projectsCached: 'Projects cached',
    version: 'Version',
    offlineOnly: 'Offline only workflow. No network upload.',
  },
  edgeCases: {
    largeVideoSwitched:
      'Large 4K source detected. Preview switched to Smooth mode for stable playback.',
    backgroundPaused: 'Preview paused in background',
    backgroundExportContinues: 'Export continues in background task mode',
    backgroundExportPaused: 'Export paused in background mode',
    assetUnavailableTitle: 'Asset unavailable',
    assetUnavailableBody:
      'The source video is no longer available locally. Relink the original to continue.',
  },
  accessibility: {
    projectCard: 'Project card',
    addRegionButton: 'Add blur region',
    timeline: 'Timeline scrubber',
    playhead: 'Timeline playhead',
    exportProgress: 'Export progress ring',
    settingsButton: 'Open settings',
    importButton: 'Import video',
    timelineModePrecision: 'Precision mode',
    timelineModeStandard: 'Standard mode',
    previewStubTitle: 'BlurioPreviewView native renderer stub',
  },
} as const;
